### ISSUE TITLE
app crashing - ReferenceError: mongoUri is not defined

### ISSUE THREAD

**Issue by rohan-paul** [shamahoque/mern-social#1]
Clone this repository
Open command line in the cloned folder,
To install dependencies, run npm install
To run the application for development, run npm run development
Open localhost:3000 in the browser

After following your instruction as above - I am getting "app crashed" and the errors seems to be about "ReferenceError: mongoUri is not defined
    at NativeConnection.eval (webpack:///./server/server.js?:21:55)
    at NativeConnection.emit (events.js:182:13)
"

**Comment by shamahoque** [comment]
This error means no running instance of MongoDB was found on your system. 
Make sure you have MongoDB running before you run the application code.
