### ISSUE TITLE
H10 error on  heroku

### ISSUE THREAD

**Issue by mariusmonkam** [shamahoque/mern-social#10]
The app is deploying well on heroku but but there is H10  error when I open it ...can you help please

2019-11-16T22:18:03.301884+00:00 heroku[web.1]: Process exited with status 1
2019-11-16T22:18:08.428625+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=app-quickinhel.herokuapp.com request_id=13864623-07bb-4288-a02f-bac9ad87cc25 fwd="84.248.64.227" dyno= connect= service= status=503 bytes= protocol=https
2019-11-16T22:18:11.753455+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=app-quickinhel.herokuapp.com request_id=b19962f1-f078-49d2-91cb-5447d78486d0 fwd="84.248.64.227" dyno= connect= service= status=503 bytes= 
protocol=https

**Comment by shamahoque** [comment]
Did you add a MongoDB instance for your Heroku app? Like install and configure a mLab MongoDB add-on on Heroku?

**Comment by mariusmonkam** [comment]
Hi Shamahoque !
I think so , may be i do it wrong , please check and let me know...i can also invite you as collaborator to make it easy to help me.
here is my package.json
`{
  "name":"quickinhel",
  "version": "1.0.0",
  "description": "",
  "author": "",
  "license": "ISC",
  "main": "./dist/server.generated.js",
  "scripts": {
    "development": "nodemon",
    "build": "webpack --config webpack.config.client.production.js && webpack --mode=production --config webpack.config.server.js",
    "start": "NODE_ENV=production node ./dist/server.generated.js"
  },

  "devDependencies": {
    "babel-core": "6.26.2",
    "babel-loader": "7.1.4",
    "babel-preset-env": "1.6.1",
    "babel-preset-react": "6.24.1",
    "babel-preset-stage-2": "6.24.1",
    "file-loader": "^4.2.0",
    "nodemon": "^1.19.4",
    "webpack": "4.6.0",
    "webpack-cli": "2.0.15",
    "webpack-dev-middleware": "3.1.3",
    "webpack-hot-middleware": "2.22.1",
    "webpack-node-externals": "1.7.2"
  },
  "dependencies": {
    "body-parser": "1.18.2",
    "compression": "1.7.2",
    "cookie-parser": "1.4.3",
    "cors": "2.8.4",
    "express": "4.16.3",
    "express-jwt": "5.3.1",
    "formidable": "1.2.1",
    "helmet": "3.12.0",
    "jsonwebtoken": "8.2.1",
    "lodash": "4.17.10",
    "material-ui": "1.0.0-beta.43",
    "material-ui-icons": "^1.0.0-beta.36",
    "mongoose": "5.0.16",
    "react": "^16.11.0",
    "react-dom": "^16.11.0",
    "react-hot-loader": "4.1.2",
    "react-router": "^5.1.2",
    "react-router-dom": "^5.1.2"
  }
}
`
here is my config


`const config = {
  env: process.env.NODE_ENV || 'production',
 port: process.env.PORT ||3000,
  jwtSecret: process.env.JWT_SECRET || "secret",
  mongoUri: process.env.MONGODB_URI ||
    process.env.MONGO_HOST ||
    'mongodb://' + (process.env.IP || 'localhost') + ':' +
    (process.env.MONGO_PORT || '27017') +
    '/mern_quickinhel'
}

export default config`

**Comment by shamahoque** [comment]
The code seems correct to me. I would re-check the configuration on the Heroku Dashboard.

**Comment by mariusmonkam** [comment]
Thanks Sent from my Huawei phone-------- Original Message --------Subject: Re: [shamahoque/mern-social] H10 error on  heroku (#10)From: Shama Hoque To: shamahoque/mern-social CC: MariusMonkam ,Author The code seems correct to me. I would re-check the configuration on the Heroku Dashboard.

**Comment by mariusmonkam** [comment]
I finally get it work , I think the problem was linked to the mongoUri setting ,  the working version is on the production branch.
