### ISSUE TITLE
Are you creating a second edition of the book?!

### ISSUE THREAD

**Issue by streetwiseherc** [shamahoque/mern-social#12]
I really like the Packt MERN book, and it looks like you're updating the sample projects and creating new ones.  I've looked on Packt's website and I haven't seen any announcement of a future title (or second edition).  What are the plans for the book?  Are you going to use all new sample projects and/or update the 1st edition projects?  I like how you use a single project for both the client and server.  Create-react-app is quite popular right now, but I prefer your method of setting up a MERN project.  Is there a release date planned for the book?

Thanks!

**Comment by shamahoque** [comment]
The second edition just came out, it is available here: https://www.packtpub.com/web-development/full-stack-react-projects-second-edition

All the first edition projects have been updated and there's a couple of new ones!

Thank you for reading! =)

**Comment by streetwiseherc** [comment]
Thanks!  I just ordered the ebook.

I'm glad I asked.  I never seem to be able to find what I'm looking for on the Packt site. :(

When I search for MERN or React, the search results still show the 1st edition. I hope they put some kind of notification on the page for the 1st edition that a 2nd edition is now available: https://www.packtpub.com/web-development/full-stack-react-projects

I do love the newer colorful Packt covers though!
