### ISSUE TITLE
Adding a scroll in Who to follow

### ISSUE THREAD

**Issue by DeepakDDC** [shamahoque/mern-social#18]
In the who to follow section. If the number of users increases the page size is increasing. I think it's not the correct form to display. 
Why don't we have a Div and scrolling available? and also let us add a searching a profile on the site. So the users can search for the other users.

**Comment by shamahoque** [comment]
The Who to follow section can be made scrollable by tweaking the CSS of the Paper component it is rendered in: 
https://github.com/shamahoque/mern-social/blob/second-edition/client/user/FindPeople.js#L91

Possible CSS options would including fixing the height and adding auto overflow, for example:
`{
    height: 600px;
    overflow: auto;
}`

The template provided here has been kept basic. Readers of the book or anyone playing with this code is welcome to modify and add features as desired. 

Note: If you are looking for an example of search implementation in this stack, it is covered in the [MERN Marketplace](https://github.com/shamahoque/mern-marketplace) project from the book with a product search feature.
