### ISSUE TITLE
Heroku

### ISSUE THREAD

**Issue by Julianbullmagic** [shamahoque/mern-social#23]
Hi Shamahoque,

I'm having a huge amount of trouble deploying my version of this to Heroku. Have you tried this? How would you do this?

**Comment by shamahoque** [comment]
Hey @Julianbullmagic,

All the live demos for my book are actually hosted on Heroku. To get this version working on Heroku:

1. You need to comment out two lines of code in the [server/express.js](https://github.com/shamahoque/mern-social/blob/second-edition/server/express.js) file before pushing the code to Heroku. Specifically, [line 24](https://github.com/shamahoque/mern-social/blob/second-edition/server/express.js#L24) and [line 30](https://github.com/shamahoque/mern-social/blob/second-edition/server/express.js#L30).
2. On your Heroku app settings make sure you add a config variable named MONGODB_URI containing the URL of the MongoDB instance your app will be connecting to. For example, if you use a cluster on MongoDB Atlas, you need to get the URL to connect your database to your app.

Getting the database connected correctly usually causes a bit of trouble if you are doing this for the first time. But this is pretty much all I had to do to get this version up on Heroku.
