### ISSUE TITLE
Cannot find module 'webpack'

### ISSUE THREAD

**Issue by tobitech** [shamahoque/mern-social#4]
I just deployed the project to heroku and i'm getting the above error. What do I need to configure the project to run on production environment?

**Comment by shamahoque** [comment]
For production, you need to update the express.js file and remove these two lines:

```
import devBundle from './devBundle'
devBundle.compile(app)
```

You can refer to the code in the 'production' branch:
https://github.com/shamahoque/mern-social/blob/production/server/express.js

**Comment by tobitech** [comment]
I was able to get this to work by adding Webpack as a main dependency. 
But another issue came up.
I get this printed in the console when I visit the web app:
`Refused to execute script from 'https://sample.herokuapp.com/dist/bundle.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.`

**Comment by shamahoque** [comment]
This usually indicates the dist/bundle.js file is missing or cannot be accessed. Make sure the file is there in the dist folder and it is being pushed to Heroku - check the .gitignore file to ensure the dist folder is not being ignored.

**Comment by tobitech** [comment]
The bundle.js file isn't there, I don't know why. Only the server.generated.js is ignored

**Comment by shamahoque** [comment]
Run `npm run build` to generate the bundle.js and server.generated.js files for production, and make sure your .gitignore file resembles this version: https://github.com/shamahoque/mern-social/blob/production/.gitignore

See if pushing these changes to Heroku make a difference. 

The code in the [production](https://github.com/shamahoque/mern-social/tree/production) branch from this repository is currently running on Heroku without any issues.

**Comment by tobitech** [comment]
Thanks you are the best. `npm run build` worked
